-- Kiểm tra cấu trúc bảng Donhang
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Donhang'
ORDER BY ORDINAL_POSITION;

-- Kiểm tra cấu trúc bảng Chitietdonhang
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Chitietdonhang'
ORDER BY ORDINAL_POSITION;
